language: node_js
sudo: true
node_js:
  - '4.1.1'
cache:
  directories:
    - node_modules
before_install:
    - npm install
script:
  - npm test
  - npm run dev
  - npm run build
notifications:
  slack: yytspace:mAvt46hmfFsPbipu3auvoUH3
after_script:
  - npm run coverage
